{% set version = "9.0" %}

package:
  name: coremltools
  version: {{ version }}

source:
  # The sdist on PyPI lacks at least
  #   - LICENSE.txt
  #   - CMakeLists.txt
  # so we use GitHub releases.
  # They would also vendor many protobuf things, which we work to unvendor here
  url: https://github.com/apple/coremltools/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0582e0307dbdccdcb4936f8b3b6880bb2e815d9a416a3e76127824bd3bec5ce6
  patches:
    - patches/0001-Use-nlohmann_json-from-conda-forge.patch
    - patches/0002-Update-CMakeLists-to-use-new-python-and-conda-forge-.patch
    - patches/0003-Avoid-building-test-code.patch
    - patches/0004-Use-strip-from-environment-variable.patch
    - patches/0005-Adjust-build-system-to-unvendor-protobuf.patch
    - patches/0006-Update-mlmodel-to-newer-absel.patch
    - patches/0007-Use-upstream-kmeans1d-always.patch
    - patches/0008-Use-python-for-enumgen-instead-of-cpp-for-cross-comp.patch

build:
  number: 0
  # The upstream package does not support Windows.
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - make
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # libprotobuf is needed for protoc
    - protobuf                               # [build_platform != target_platform]
    - libprotobuf                            # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - numpy
    - pybind11
    - nlohmann_json
    - zlib
    - protobuf
    - libprotobuf
    - libprotobuf-python-headers
    - libabseil
  run:
    - python
    # TODO: Check numpy minimum and other dependencies too
    - numpy >=1.21
    - protobuf >=3.1.0
    - sympy
    - tqdm
    - packaging
    - attrs >=21.3.0
    - cattrs
    - pyaml
    # Optional but seems to provide a few features
    - scipy
    # Not listed on pypi recipe, but it is there in Version 7.1's conda pacakge upstream
    # https://github.com/apple/coremltools/blob/main/scripts/conda/meta.yaml
    - libuuid  # [linux]
    # we unvendored their version of kmeans1d
    - kmeans1d
  run_constrained:
    - pytorch >=1.4

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - coremltools
    # required for predict() on macOS
    - coremltools.libcoremlpython  # [osx]

about:
  home: https://github.com/apple/coremltools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Core ML is an Apple framework to integrate machine learning models into your app. Core ML provides a unified representation for all models.

  description: |
    Core ML is an Apple framework to integrate machine learning models into your app.

    Use the coremltools Python package to convert models from third-party training libraries such as TensorFlow and PyTorch to the Core ML format. You can then use Core ML to integrate the models into your app.

    Core ML provides a unified representation for all models. Your app uses Core ML APIs and user data to make predictions, and to fine-tune models, all on the user’s device. Running a model strictly on the user’s device removes any need for a network connection, which helps keep the user’s data private and your app responsive.

    Core ML optimizes on-device performance by leveraging the CPU, GPU, and Neural Engine while minimizing its memory footprint and power consumption.
  doc_url: https://coremltools.readme.io/docs
  dev_url: https://github.com/apple/coremltools

extra:
  recipe-maintainers:
    - 1duo
    - aseemw
    - seibert
    - TobyRoseman
    - hmaarrfk
