{% set version = "8.1" %}

package:
  name: coremltools
  version: {{ version }}

source:
  # The sdist on PyPI lacks at least
  #   - LICENSE.txt
  #   - CMakeLists.txt
  # so we use GitHub releases.
  url: https://github.com/apple/coremltools/archive/refs/tags/{{ version }}.tar.gz
  sha256: fd8e2f399a36b0870ba41b029decd7e619f04c91905d18ad703020778237795f
  patches:
    - patches/0001-Use-nlohmann_json-from-conda-forge.patch
    # - patches/0002-Include-memory-header-in-JsonMap.patch
    - patches/0003-Update-CMakeLists-to-use-new-python-and-conda-forge-.patch
    - patches/0004-Avoid-building-test-code.patch

build:
  number: 0
  # The upstream package does not support Windows.
  skip: true  # [win]
  # Just build 1 python build until we are ready to finally release the package
  skip: true  # [py != 312]

requirements:
  build:
    - autoconf                               # [build_platform != target_platform]
    - automake                               # [build_platform != target_platform]
    - libtool                                # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - make
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - pip
    - pybind11
    - nlohmann_json
    - zlib
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - protobuf >=3.1.0
    - sympy
    - tqdm
    - packaging
    - attrs >=21.3.0
    - cattrs
    - pyaml
    # Optional but seems to provide a few features
    - scipy
    # Not listed on pypi recipe, but it is there in Version 7.1's conda pacakge upstream
    # https://github.com/apple/coremltools/blob/main/scripts/conda/meta.yaml
    - libuuid  # [linux]
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]
    - pytorch >=1.4

test:
  imports:
    - coremltools
    # required for predict() on macOS
    - coremltools.libcoremlpython  # [osx]

about:
  home: https://github.com/apple/coremltools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Core ML is an Apple framework to integrate machine learning models into your app. Core ML provides a unified representation for all models.

  description: |
    Core ML is an Apple framework to integrate machine learning models into your app.

    Use the coremltools Python package to convert models from third-party training libraries such as TensorFlow and PyTorch to the Core ML format. You can then use Core ML to integrate the models into your app.

    Core ML provides a unified representation for all models. Your app uses Core ML APIs and user data to make predictions, and to fine-tune models, all on the user’s device. Running a model strictly on the user’s device removes any need for a network connection, which helps keep the user’s data private and your app responsive.

    Core ML optimizes on-device performance by leveraging the CPU, GPU, and Neural Engine while minimizing its memory footprint and power consumption.
  doc_url: https://coremltools.readme.io/docs
  dev_url: https://github.com/apple/coremltools

extra:
  recipe-maintainers:
    - 1duo
    - aseemw
    - seibert
    - TobyRoseman
